'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import { Navbar } from "@/components/shared/Navbar/Navbar";
import Footer from "@/components/shared/Footer/Footer";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "BD Health Care",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();
  const isDashboard = pathname?.startsWith("/dashboard");

  console.log(pathname, ' p name');
  return (
    <html lang="en">
      <body className={inter.className}>
      {!isDashboard && <Navbar />}
        <Providers>{children}</Providers>
        {!isDashboard && <Footer />}
      </body>
    </html>
  );
}
